In [2]:
import numpy as np

In [3]:
arr=np.array([1,2,3,4])
arr

array([1, 2, 3, 4])

In [4]:
def hello():
    print("my name is lalit")

In [5]:
hello()

my name is lalit


In [6]:
l= [1,2,3,4]
l

[1, 2, 3, 4]

In [10]:
a = [1,2.0,5]
a

[1, 2.0, 5]

In [11]:
b = np.array(a)
b

array([1., 2., 5.])

In [13]:
l = [[1,2,3],[4,5,6],[7,8,9]]
l

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [14]:
np.array(l)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [16]:
arr = np.arange(1,11,2)
arr

array([1, 3, 5, 7, 9])

In [17]:
arr = np.zeros(5)
arr

array([0., 0., 0., 0., 0.])

In [18]:
arr = np.zeros((3,3))
arr

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [19]:
arr = np.ones(5)
arr

array([1., 1., 1., 1., 1.])

In [20]:
arr = np.ones((3,3))
arr

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [24]:
arr = np.linspace(1,5,10)
arr

array([1.        , 1.44444444, 1.88888889, 2.33333333, 2.77777778,
       3.22222222, 3.66666667, 4.11111111, 4.55555556, 5.        ])

In [27]:
np.random.rand(5) 

array([0.7055166 , 0.85659315, 0.6374927 , 0.58537066, 0.48804301])

In [29]:
np.random.randn(10)

array([ 0.10647214, -0.69408298, -1.08689929, -1.31109893, -0.61440014,
       -0.37474548, -0.61439128,  0.93751177, -0.35485243,  0.68664093])

In [35]:
np.random.randint(10,20,5)

array([15, 19, 18, 12, 10], dtype=int32)

In [37]:
arr = np.array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [38]:
arr.shape

(3, 3)

In [39]:
arr.size

9

In [40]:
arr.dtype

dtype('int64')

In [41]:
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [42]:
arr.min()

np.int64(1)

In [43]:
arr.max()

np.int64(9)

In [44]:
arr.sum()


np.int64(45)

In [46]:
np.sum(arr,axis=1)

array([ 6, 15, 24])

In [47]:
arr.mean()

np.float64(5.0)

In [48]:
arr.std()

np.float64(2.581988897471611)

In [49]:
arr.argmax()

np.int64(8)

In [50]:
arr.argmin()

np.int64(0)

In [51]:
arr = np.arange(1,31)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30])

In [52]:
arr.reshape(6,5)

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30]])

In [53]:
arr = arr.reshape(6,5)

In [54]:
arr

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30]])