In [2]:
import numpy as np

In [3]:
arr = np.arange(1,11)

In [4]:
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [5]:
arr[0]

np.int64(1)

In [6]:
arr[8]

np.int64(9)

In [7]:
arr[9]

np.int64(10)

In [8]:
arr[1:5]

array([2, 3, 4, 5])

In [9]:
arr[:5]

array([1, 2, 3, 4, 5])

In [10]:
arr[:]

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [11]:
arr[1:]

array([ 2,  3,  4,  5,  6,  7,  8,  9, 10])

In [12]:
arr[0::2]

array([1, 3, 5, 7, 9])

In [13]:
arr = np.arange(1,10)
arr

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [14]:
arr = arr.reshape(3,3)

In [15]:
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [16]:
arr = np.arange(1,31).reshape(6,5)
arr

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30]])

In [17]:
arr[0]

array([1, 2, 3, 4, 5])

In [18]:
arr[0,1]

np.int64(2)

In [19]:
arr[5]

array([26, 27, 28, 29, 30])

In [20]:
arr[0]

array([1, 2, 3, 4, 5])

In [21]:
arr[0,0]

np.int64(1)

In [22]:
arr.shape

(6, 5)

In [23]:
arr.size

30

In [24]:
arr[0,0]

np.int64(1)

In [25]:
arr[0]

array([1, 2, 3, 4, 5])

In [26]:
arr

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30]])

In [27]:
slice  = arr[0:2,1:3]
slice 

array([[2, 3],
       [7, 8]])

In [28]:
slice  = arr[:,2]
slice 

array([ 3,  8, 13, 18, 23, 28])

In [37]:
arr = np.arange(1,31).reshape(6,5)
s = arr[3:,3:]
s


array([[19, 20],
       [24, 25],
       [29, 30]])

In [29]:
arr  = np.arange(11,21)
arr

array([11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [30]:
bool_index  = arr % 2 == 0
bool_index


array([False,  True, False,  True, False,  True, False,  True, False,
        True])

In [31]:
arr = arr[bool_index]
arr

array([12, 14, 16, 18, 20])