In [1]:
import numpy as np

In [25]:
a1 = np.arange(1,5)
a2 = np.arange(6,10)
a2


array([6, 7, 8, 9])

In [26]:
arr1 = a1 + a2

In [27]:
l = [10,20,30,40]
arr = np.array(l)
arr

array([10, 20, 30, 40])

In [28]:
l + 10

TypeError: can only concatenate list (not "int") to list

In [29]:
arr + 10

array([20, 30, 40, 50])

In [30]:
a = np.arange(1,21)
a


array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [31]:
slice = a[:5]
slice = slice * 10
slice 

array([10, 20, 30, 40, 50])

In [32]:
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [33]:
a1

array([1, 2, 3, 4])

In [34]:
a2

array([6, 7, 8, 9])

In [35]:
A = a1.reshape(2,2)
B = a2.reshape(2,2)


In [36]:
A

array([[1, 2],
       [3, 4]])

In [38]:
B

array([[6, 7],
       [8, 9]])

In [39]:
A * B

array([[ 6, 14],
       [24, 36]])

In [40]:
A @ B

array([[22, 25],
       [50, 57]])

In [41]:
A


array([[1, 2],
       [3, 4]])

In [42]:
A.T


array([[1, 3],
       [2, 4]])

In [43]:
a1

array([1, 2, 3, 4])

In [44]:
a2

array([6, 7, 8, 9])

In [45]:
np.vstack((a1,a2))


array([[1, 2, 3, 4],
       [6, 7, 8, 9]])

In [46]:
np.hstack((a1,a2))

array([1, 2, 3, 4, 6, 7, 8, 9])

In [48]:
np.column_stack((a1,a2))

array([[1, 6],
       [2, 7],
       [3, 8],
       [4, 9]])

In [49]:
c = np.arange(1,17).reshape(4,4)
c

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [54]:
np.hsplit(c,4)

[array([[ 1],
        [ 5],
        [ 9],
        [13]]),
 array([[ 2],
        [ 6],
        [10],
        [14]]),
 array([[ 3],
        [ 7],
        [11],
        [15]]),
 array([[ 4],
        [ 8],
        [12],
        [16]])]

In [55]:
np.vsplit(c,2)

[array([[1, 2, 3, 4],
        [5, 6, 7, 8]]),
 array([[ 9, 10, 11, 12],
        [13, 14, 15, 16]])]